tmp commit

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10,29 +10,62 @@ browser_list=(
     "firefox"
 )
 
+function env_config() {
+    browser_path=$1
+
+    # Create config file
+    rm -f "${config_file}"
+    echo -e "#!/bin/bash\n" >> "${config_file}"
+    echo "browser=${browser_path}" >> "${config_file}"
+    echo "tmp_col_file=${tmp_col_file}" >> "${config_file}"
+    echo "col_file=${col_file}" >> "${config_file}"
+
+    # Create symbolic link
+    rm -f "${s_link}" || (echo "Remove symbolic link failed" && exit 1)
+    ln -s $(pwd)/swcomic.sh "${s_link}" || (echo "Create symbolic link failed" && exit 1)
+
+    echo "Configuration Finished"
+    exit 0
+}
+
 if [ "$EUID" -ne 0 ]; then
     echo "Please run as root"
     exit 1
 fi
 
+while getopts "btc:" opt; do
+    case "${opt}" in
+    t)
+        tmp_col_file=$OPTARG
+        ;;
+    c)
+        col_file=$OPTARG
+        ;;
+    b)
+        #echo $OPTARG
+        browser_path=$2
+        env_config "${browser_path}"
+        ;;
+    esac
+done
+
+while getopts "b:" opt; do
+    case "${opt}" in
+    b)
+        browser_path="$OPTARG"
+        env_config "${browser_path}"
+    esac
+done
+
+
+
+
 for browser in "${browser_list[@]}"; do
     browser_path=$(which "${browser}")
     if [[ $? -eq 0 ]]; then
         echo "Find ${browser}"
+        env_config "${browser_path}"
 
-        # Create config file
-        rm -f "${config_file}"
-        echo -e "#!/bin/bash\n" >> "${config_file}"
-        echo "browser=${browser_path}" >> "${config_file}"
-        echo "tmp_col_file=${tmp_col_file}" >> "${config_file}"
-        echo "col_file=${col_file}" >> "${config_file}"
-
-        # Create symbolic link
-        rm -f "${s_link}" || (echo "Remove symbolic link failed" && exit 1)
-        ln -s $(pwd)/swcomic.sh "${s_link}" || (echo "Create symbolic link failed" && exit 1)
-
-        echo "Configuration Finished"
-        exit 0
     fi
 done
 
